services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: tasks
    volumes:
      - .data/:/var/lib/mysql
    ports:
      - 3306:3306

  backend:
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasks-app
    networks:
      - default
    ports:
      - "8080:8080"
    env_file:
      - .env

    volumes:
      - .:/code